# evaluation.yaml 用于配置打分程序

# 风格: [bartolome-esteban-murillo, chinese-art, claude-monet, vincent-van-gogh]
style: "claude-monet"

# 风格打分模型
model:
  # 风格打分模型是否需要训练, 需要则提供数据集路径
  model_train: False
  # 风格打分模型可区分的类名
  classes: ["bartolome-esteban-murillo", "chinese-art", "claude-monet", "vincent-van-gogh"]
  # 风格打分模型路径
  model_path: "../output/ResNet18_fix_0.949.pth"
  # 训练风格打分模型数据集路径
  dataset: "../datasets/style_classification"


