# 模板 - config.yaml 用于配置 MetaNet 的超参数

# 是否启用 swanlab 记录
swanlab:
  enable: True

# 模型保存路径
model_save_path: "../results/models"

# 注意力机制： "channel", "enhanced_channel",  "self", "transformer"
attention: "channel"

# 预训练的 VGG 模型版本，16 或 19
vgg_version: 19

training:
  # 训练轮数
  epochs: 100
  # 批次大小
  batch_size: 8
  # 学习率
  learning_rate: 0.001
  # 风格权重
  style_weight: 150
  # 内容权重
  content_weight: 1
  # 梯度平滑权重
  tv_weight: 0.000001
  # 间隔多少 batch 换一张风格照片
  style_interval: 10
  # 间隔多少轮记录一次
  record_per_epochs: 10

  base: 32

test:
  # 测试批次大小
  test_batch: 4

data:
  # 内容数据集路径
  content_dir: "../datasets/coco2017"
  # 风格数据集路径
  style_dir: "../datasets/WikiArt2"
  # 数据集处理线程
  num_workers: 4
