# config.yaml

swanlab:
  enable: false

training:
  # 训练轮数
  epochs: 100
  # 批次大小
  batch_size: 4
  # 学习率
  learning_rate: 0.001
  # 风格权重
  style_weight: 50
  # 内容权重
  content_weight: 1
  # 梯度平滑权重
  tv_weight: 0.000001
  # 间隔多少轮记录一次
  record_per_epochs: 5

  base: 32

test:
  # 测试批次大小
  test_batch: 4

data:
  # 内容数据集路径
  content_dir: "../dataset/coco2017_100"
  # 风格数据集路径
  style_dir: "../dataset/WikiArt2_100"
  num_workers: 4
